In [80]:
import numpy as np

In [81]:
print(np.__version__)

1.18.1


<h1>Basic</h1>

In [82]:
x=3
print(type(x))
print(x)
print(x+1)
print(x-1)
print(x*2)
print(x**2)
x+=1
print(x)
x*=2
print(x)
y=2.5
print(type(y))
print(y,y+1,y+2,y**2)

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 4.5 6.25


In [83]:
t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not f)
print(t!=f)

<class 'bool'>
False
True
True
True


In [84]:
hello = "hello"
world = "world"
print(hello)
print(len(hello))
hw = hello + ' ' + world
print(hw)
hw12 = "%s %s %d" % (hello,world,12)
print(hw12)

hello
5
hello world
hello world 12


In [85]:
s= "hello"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l','(ell)'))
print('   world '.strip())

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


<h1>Containers</h1>

In [86]:
xs = [3,1,2]
print(xs,xs[2])
print(xs[-1])
xs[2] = 'foo'
print(xs)
xs.append('bar')
print(xs)
x = xs.pop()
print(x)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar


<h2> SLcing</h2>

In [87]:
nums = list(range(5))
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[-3:-1])
nums[2:4] = [8,9]
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[2, 3]
[0, 1, 8, 9, 4]


In [88]:
animals = ['cat','dog','monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [89]:
nums = [0,1,2,3,4]
squares = []
for x in nums:
    squares.append(x**2)
print(squares)

[0, 1, 4, 9, 16]


In [90]:
even_squares = [x**2 for x in nums if x%2 == 0]
print(even_squares)

[0, 4, 16]


In [91]:
d = {'cat':'cute','dog':'furry'}
print(d['cat'])
print('cat' in d)
d['fish'] = 'wet'
print(d['fish'])
print(d.get('monkey','n/a'))
print(d.get('fish','n/a'))
del d['fish']
print(d.get('fish','n/a'))

cute
True
wet
n/a
wet
n/a


In [92]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [93]:
for animal,leg in d.items():
    print("%s %s"%(animal,leg))

person 2
cat 4
spider 8


In [94]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


In [95]:
animals = {'cat','dog'}
print('cat' in animals)
print('fish' in animals)
animals.add('fish')
print('fish' in animals)
print(len(animals))
animals.add('cat')
print(animals)
animals.remove('cat')
print(animals)

True
False
True
3
{'dog', 'cat', 'fish'}
{'dog', 'fish'}


In [96]:
animals = {'cat','dog','fish'}
for idx,animal in enumerate(animals):
    print('#%d : %s'%(idx+1,animal))
           

#1 : dog
#2 : cat
#3 : fish


In [97]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(26)}
print(nums)

{0, 1, 2, 3, 4, 5}


In [98]:
d = {(x,x+1): x for x in range(10)}
print(d)
t =(5,6)
print(type(t))
print(d[t])
print(d[(1,2)])

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
<class 'tuple'>
5
1


<h1>functions</h1>

In [99]:
def sign(x):
    if x>0:
        return 'positive'
    elif x<0:
        return 'negative'
    else:
        return 'zero'

for x in [-1,0,1]:
    print(sign(x))

negative
zero
positive


In [100]:
def hello(name,loud=False):
    if loud:
        print('HELLO : %s' %name.upper())
    else:
        print('hello, %s' %name)
hello('Bob')
hello('Fred',loud = True)

hello, Bob
HELLO : FRED


<h1>Classes</h1>


In [101]:
class Greeter(object):
    def __init__(self,name):
        self.name=name
    
    def greet(self,loud=False):
        if loud:
            print('HELLO : %s' %self.name.upper())
        else:
            print('hello, %s' %self.name)

g = Greeter('Fred')
g.greet()
g.greet(loud=True)

hello, Fred
HELLO : FRED


# End python
# Begin Numpy


In [112]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = 5
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b)
print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


In [123]:
a = np.zeros((2,2))
print(a)
c= (1,2)
b = np.ones(c)
print(b)
c = np.full((2,2),7)
print(c)
d= np.eye(2)
print(d)
e= np.random.random((2,2))
print(e)
f = np.linspace(1,3,10)
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.36509576 0.13459859]
 [0.48634837 0.54839405]]
[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [125]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b= a[:2,1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [128]:
print(a[0,1])
b[0,0]=77
print(a[0,1])
#modyfying sliced modifies original

77
77


In [132]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1,:]
row_r2 = a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)

col_c1 = a[:,1]
col_c2=a[:,1:2]
print(col_c1,col_c1.shape)
print(col_c2,col_c2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [139]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))
#one element can be used again
print(a[[0,0],[1,1]])

[1 4 5]
[1 4 5]
[2 2]


In [143]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0,2,0,1])
c = np.array([0,1,2,3])
print(a[np.arange(4),b])
print(a[c,b])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[ 1  6  7 11]


In [146]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a>2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [149]:
x = np.array([1, 2])   
print(x.dtype)         

x = np.array([1.0, 2.0])   
print(x.dtype)            

x = np.array([1, 2], dtype=np.int32)   
print(x.dtype)  

int64
float64
int32


# Array Math

In [159]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x * y) #element wise
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))#elemnet wise

print(np.sqrt((x)))#element wise

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [172]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(x)
print(y)
print(v)
print(w)

print(v.dot(w))
print(np.dot(v,w))
print(9*11 + 10*12)

print(x.dot(v)) #matrix product
print(np.dot(x,v))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]
219
219
219
[29 67]
[29 67]


In [178]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

10
[4 6]
[3 7]


In [182]:
print(x)
print(x.T)
v = np.array([1,2,3])
print(v)
print(v.T)
print(v.shape)
print(v.T.shape)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
(3,)
(3,)


# broadcasting

In [183]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

c=  np.empty_like(x)

for i in range(x.shape[0]):
    c[i,:]=x[i,:]+v
print(c)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [187]:
vv= np.tile(v,(4,1))
d = x+vv
print(vv)
print(d)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [188]:
e = x+v
print(e)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting two arrays together follows these rules:

If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

The arrays can be broadcast together if they are compatible in all dimensions.

After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.

In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


In [201]:
v = np.array([1,2,3]) 
w = np.array([4,5]) 

print(np.reshape(v,(3,1)))
print(np.reshape(v,(3,1))*w)

x = np.array([[1,2,3],[4,5,6]])
print(x+v)
#add to column
print(x.T)

print((x.T+w).T)

print(x + np.reshape(w,(2,1)))

print(x*2)

[[1]
 [2]
 [3]]
[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[1 4]
 [2 5]
 [3 6]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
